name: metamag
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.9
  - fastqc=0.11.9
  - multiqc=1.13
  - trimmomatic=0.39
  - bowtie2=2.4.5
  - samtools=1.15
  - idba=1.1.3
  - megahit=1.2.9
  - quast=5.2.0
  - metabat2=2.15
  - maxbin2=2.2.7
  - concoct=1.1.0
  - das_tool=1.1.3
  - metawrap=1.3.2
  - checkm2=1.0.1
  - drep=3.2.2
  - gtdbtk=2.1.1
  - kraken2=2.1.2
  - bracken=2.7
  - eggnog-mapper=2.1.9
  - dbcan=3.0.6
  - pandas=1.4.3
  - numpy=1.22.4
  - matplotlib=3.5.2
  - seaborn=0.11.2
  - pyyaml=6.0
  - biopython=1.79
  - snakemake=7.8.0
  - pip=22.1.2
  - pip:
    - pysam==0.19.1